### ISSUE TITLE
Cannot specify where compilers are

### ISSUE THREAD

**Issue by ghost** [open-power/sbe#3]
All the GCC-TOOL-PATH logic in src/build/img_defs.mk does not seem to lead to a way to specify cross compilers as simply as ``CROSS=powerpc-eabi- make`` or similar. It's thus impossible to build with an installed toolchain.

**Comment by sgupta2m** [comment]
If we want to override  PPE42PATH GCC-TOOL-PATH, we can define PPE42PATH. GCC-TOOL_PATH is only used in PPE42PATH is not defined.

We can use comamnd liks this to build sbe using an installed tool chain

make LD_LIBRARY_PATH=<PATH> PPE42PATH=<GCC Bin PATH> all

**Comment by ghost** [comment]
Running that exact command:

```
sh: /afs/awd/projects/cte/tools/ppetools/prod/bin/powerpc-eabi-gcc: No such file or directory
sh: /afs/awd/projects/cte/tools/ppetools/prod/bin/powerpc-eabi-gcc: No such file or directory
```

**Comment by sgupta2m** [comment]
what is the command u have exactly given .. what is the path for you installed libarries

make LD_LIBRARY_PATH=<path> PPE42PATH=<path> all

**Comment by sgupta2m** [comment]
somehow it removes whatever i message in angurla brackets ( <> ). So the exact comamnd, using double quite ..
make LD_LIBRARY_PATH="path" PPE42PATH="path" all

**Comment by ghost** [comment]
Okay, so that makes it start to look for things in the right places.

I'd say that going with a more conventional CROSS= or CROSS_COMPILE= with that being the prefix to the toolchain it'd be easier for people.

e.g.
`CROSS=powerpc-eabi- make`
or
`CROSS=/opt/cross/powerpc-eabi/bin/powerpc-eabi- make`

**Comment by sgupta2m** [comment]
Changes done
