### ISSUE TITLE
Latest SBE image causes IPL loop on DD2.1

### ISSUE THREAD

**Issue by madscientist159** [open-power/sbe#7]
Using the latest SBE sources (9b03db45c424d6edc5698fa74830dc1d432fdfe8) to build an SBE results in an IPL loop on our single and dual CPU DD2.1 systems.  Each loop hostboot attempts to update the SBE and re-IPL, and each time the CPU switches to the backup side 1 SBE image.  Also, the second CPU is knocked offline and requires SBE re-initialization and clearing of the XBUS GARD entries in hostboot when downgrading the SBE to a known working version.

Reverting to c68fb43ecf21c311d912b89dbc0f55d49ec78bc4 allows both CPUs to IPL.

**Comment by sgupta2m** [comment]
we will need console output/ esel output to debug it further.

**Comment by sgupta2m** [comment]
Is there any further update on this. Are you getting this issue on latest sbe

**Comment by madscientist159** [comment]
Latest SBE is not even working due to #10

**Comment by sgupta2m** [comment]
Is it same as #10 and we can close this.

**Comment by madscientist159** [comment]
No, this is a different issue.  This one is the BMC switching to side 1 of the SBE to IPL from after the second SBE side 0 update.  Since it's IPLing from side 1, we enter a loop of trying to update side 0 and re-IPL.

**Comment by sgupta2m** [comment]
ok .. do u have failed data in this case. HB traces, eSel output

**Comment by madscientist159** [comment]
Not at the moment.  The priority right now is getting DD2.2 to successfully IPL, and hostboot bugs https://github.com/open-power/hostboot/issues/128 and https://github.com/open-power/hostboot/issues/129 are blocking that.

**Comment by sgupta2m** [comment]
ok please let us know when u want us to debug it ..

**Comment by madscientist159** [comment]
Will do; thanks for being patient :smile:

**Comment by sgupta2m** [comment]
I will close this issue. Please reopen once you get chance to work  on it.

**Comment by madscientist159** [comment]
I think I found the origin of the problem.  On the BMC, BOOT_COUNT_MAX_ALLOWED is only set to 3 by default, which is not enough to complete a full SBE update (three IPL attempts are required just to complete the update cycle, 1 on the old SBE and 2 on the new SBE).  A quick hack would be to just change BOOT_COUNT_MAX_ALLOWED to 4.

**Comment by sgupta2m** [comment]
I think it only requires 2 IPL in SBE image update case. One with old SBE  and than next IPL with new SBE. 
@dcrowell77 can you please comment.

**Comment by madscientist159** [comment]
@sgupta2m We're consistently seeing the following:
Boot 1: Old SBE IPL from SBE side 0, updates in ISTEP7
Boot 2: Hybrid SBE IPL from SBE side 1, updates further in ISTEP10
Boot 3: Falls back to SBE side 1 due to counter expiring.  Should have booted from SBE side 0 and updated SBE side 1.  Tries to update SBE again, but will never IPL from side 0 until the BMC host control service is rebooted (forcibly resetting the counter).

A more pertinent question would be: how does hostboot signal a "good boot" and get the counter reset?  I think some of what's going wrong is that occasionally there is a missed boot (between boot 1 and boot 2 above) that increments the counter one time too many even though it's a recoverable situation.

**Comment by dcrowell77** [comment]
It doesn't matter what the bootcount is set to in this case.  Hostboot always resets it back to the default (via ipmi message to the bmc) before triggering the reboot to run on the new image.  We do the same thing for any of our 'reconfig loop' reboot requests.

Which kind of system is this on?  There may be some differences/bugs in the different BMC implementations.  Based on the submitter I'm guessing this is on a Romulus-ish system.  Is it running OpenBMC or AMI code?

**Comment by madscientist159** [comment]
@dcrowell77 OK, then the reset is not working.  This is on an OpenBMC system, slightly older BMC code but latest and greatest hostboot:

https://git.raptorcs.com/git/talos-openbmc/

**Comment by dcrowell77** [comment]
Any chance you could get Hostboot traces from this scenario?  And/or BMC logs?  There should be an indication that we send the 'reset boot count' command down before we triggered the shutdown.

@geissonator - Can you comment?  Any known fixes not in their level?

**Comment by madscientist159** [comment]
@dcrowell77 Yes, we can do that.  As you can probably tell this bug is somewhat low priority so we haven't even really had a chance to dig into it internally aside from figuring out enough to run workarounds on the manufacturing line.

**Comment by madscientist159** [comment]
@dcrowell77 Standard hostboot logs don't reveal too much:

```
 58.47774|sbe|System Performing SBE Update for PROC 1, side 0
 79.80388|sbe|System Rebooting To Complete SBE Update Process
 79.81088|IPMI: Initiate power cycle
 79.86496|Stopping istep dispatcher
 81.55802|IPMI: shutdown complete
```

Might need a debug build which would take longer to get data from at this point.
