### ISSUE TITLE
Build is not paralellized

### ISSUE THREAD

**Issue by madscientist159** [open-power/sbe#9]
The SBE build runs sequentially on one core, taking far too long to build and wasting system resources.  It should support parallel make.

**Comment by sgupta2m** [comment]
Its a known issue in SBE.  But SBE build is generally fast ( takes 6-7 mins ).

**Comment by ghost** [comment]
With https://github.com/open-power/op-build/commit/82f33c72e5093d9147c828a2b92447bf79811564 we can now close this issue.
